[package]
name = "replicator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.4"
eframe = "0.21.3"
egui_extras = "*"
rand = "*"
image = "0.24.6"
csv = "*"
